package datasource

import (
	"context"
	"math/rand"
	"strconv"
	"time"

	"github.com/google/go-github/v34/github"
	"github.com/inburst/prty/logger"
)

// I was not able to get token generation automated 😢

// randString returns a (kinda) random string for uniqueness purposes.
func randString() string {
	return strconv.FormatInt(rand.NewSource(time.Now().UnixNano()).Int63(), 10)
}

func GenerateAccessToken() {
	InitSharedClient("")
	//sharedClient().

	rand := randString()
	auth := &github.AuthorizationRequest{
		Note:        github.String("Personal token: Note generated by test: " + rand),
		Scopes:      []github.Scope{github.ScopeRepo, github.ScopeReadOrg},
		Fingerprint: github.String("Personal token: Fingerprint generated by test: " + rand),
	}

	ctx := context.Background()
	got, _, err := sharedClient().Authorizations.CreateImpersonation(ctx, "u", auth)
	logger.Shared().Printf("%+v %+v", got, err)
}
